# Generated by Django 5.1.4 on 2024-12-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgrupo',
            name='name',
            field=models.CharField(default='Grupo A', max_length=100),
        ),
    ]
