# Generated by Django 5.1.4 on 2024-12-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_parentchild_delete_parentstudentrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgrupo',
            name='subject',
            field=models.CharField(default='Matematica', max_length=100),
        ),
    ]
